plugins:

  # Determine the type of release by analyzing commits.
  # ie: Major, Minor or Patch
  - "@semantic-release/commit-analyzer"

  # Generate CHANGELOG.md
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"

  # Build the release artifacts
  # This includes tarballs, rpms/debs, docker images, etc
  - - "@semantic-release/exec"
    - prepareCmd: "make release VERSION=${nextRelease.version} COMMIT=${commits.commit.long} DATE=${Date.now()}"

  # Commit CHANGELOG.md back to repo
  - - "@semantic-release/git"
    - assets: [ CHANGELOG.md ]
      message: "chore(release): update changelog [skip ci]"

  # Create new github release
  - - "@semantic-release/github"
    - assets:
        - path: "./dist/**/*"
        - path: "./dist/**/*.*"

  # Run final publish tasks, such as docker push
  - - "@semantic-release/exec"
    - publishCmd: "make publish"
