# Yaml Spec: https://aka.ms/yaml

jobs:
  - job: lint_commitlint
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ../steps/restore-node-deps.yml

      - bash: git checkout master && git checkout -
        displayName: Make git repo compatible with commitlint

      - bash: pnpx commitlint --from="master^1" --to="$(Build.SourceVersion)"
        displayName: Lint Commit Messages
