# Yaml Spec: https://aka.ms/yaml

jobs:
  - job: release
    pool:
      vmImage: ubuntu-16.04
    dependsOn:
      - lint_commitlint
      - test_linux
      - test_windows
      - test_macos
    steps:
      - checkout: self
        persistCredentials: true

      - template: ../steps/restore-node-deps.yml

      - template: ../steps/restore-golang-deps.yml

      - bash: go install github.com/phogolabs/parcello/cmd/parcello
        displayName: Install github.com/phogolabs/parcello

      - bash: pnpx semantic-release
        displayName: Run semantic-release
        env:
          GITHUB_TOKEN: $(github.token)
