# Yaml Spec: https://aka.ms/yaml

parameters:
  name: ''
  vmImage: ''
  cover: false

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - template: ../steps/restore-golang-deps.yml

      - ${{ if eq(parameters.cover, true) }}:
        - bash: go test -race -cover -covermode=atomic -coverprofile=generator.cover ./generator
          displayName: Test generator with coverage

        - bash: go test -race -cover -covermode=atomic -coverprofile=executor.cover ./executor
          displayName: Test executor with coverage

        - bash: >-
            cat generator.cover >> coverage.txt && cat executor.cover >> coverage.txt &&
            bash <(curl -s https://codecov.io/bash)
          displayName: Publish Code Coverage Reports to codecov.io
          env:
            CODECOV_TOKEN: $(codecov.token)

      - ${{ if eq(parameters.cover, false) }}:
        - bash: go test -race ./generator
          displayName: Test generator

        - bash: go test -race ./executor
          displayName: Test executor
