// Code generated by parcello-typed; DO NOT EDIT.

package resources

// Typed is a struct that represents the embedded parcello filesystem.
// It is a singleton object and is initialized for you, just use it.
var Typed *typedFileSystem

// UnTyped provides a dynamic interface into the embedded parcello filesystem.
func UnTyped(path string) *TypedFile {
	return typedFileFactory(path)
}

type typedFileSystem struct {
	MakefileGeneratedGotmpl *TypedFile
}

func init() {
	Typed = &typedFileSystem{}
	Typed.MakefileGeneratedGotmpl = typedFileFactory("makefile_generated.gotmpl")
}
